# Gallformers Status Page Configuration
owner: jeffdc
repo: gallformers-status

sites:
  - name: Gallformers V2 API
    url: https://gallformers.fly.dev/health
    expectedStatusCodes:
      - 200
  - name: Gallformers V2 Site
    url: https://gallformers.fly.dev
    expectedStatusCodes:
      - 200
  - name: Gallformers CloudFront CDN
    url: https://dfd18lb16qtjl.cloudfront.net/health
    expectedStatusCodes:
      - 200
  - name: Gallformers (Production)
    url: https://gallformers.org
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /gallformers-status
  logoUrl: https://gallformers.org/images/gflogo.png
  name: Gallformers Status
  introTitle: "**Gallformers** service status"
  introMessage: Real-time uptime monitoring for gallformers.org services.
  navbar:
    - title: Status
      href: /
    - title: Gallformers
      href: https://gallformers.org
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Check every 5 minutes
workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 0 * * *"

# Create GitHub issues for incidents
i18n:
  activeIncidents: Active incidents
  allSystemsOperational: All systems operational
  incidentReport: Incident report for {0}

# Commit settings
commitMessages:
  commitAuthorName: Upptime Bot
  commitAuthorEmail: upptime@gallformers.org
